
[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  command = "npm run dev"
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
